### ISSUE TITLE
Change 'xrange' to 'range' in the function 'find_average_precision' for python 3 users

### ISSUE THREAD

**Issue by devraj89** [dkaterenchuk/ranking_measures#2]
Hi

Thanks for the wonderful code.
Any plans for implementing this in MATLAB ?
Also, is there any implementation for Kendall's Tau ?

Thanks in Advance!
Devraj

**Comment by dkaterenchuk** [comment]
Hi Devraj,
Thanks for pointing it out! The problem is fixed and it should work with both python 2 and 3. 
For Kendall's Tau, I would refer you to python's scipy package (https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.kendalltau.html?highlight=kendall). 
I wasn't planning on implementing it in other languages. But will take a look if I can get access to a MATLAB computer.

Thanks!
Denys
